export const RESPONSE_MESSAGES = {
  COMMON: {
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    REQUIRED_FIELDS: 'All fields are required.',
    SOMETHING_WRONG: 'Something went wrong',
  },
  USERS: {
    SIGNED_UP: 'New user created',
    SIGNED_IN: 'Successfully signed in',
    SIGNED_OUT: 'Successfully signed out',
    USER_EMAIL_EXISTS: 'Email already exists',
    USER_USERNAME_EXISTS: 'Username already exists',
    EMAIL_ALREADY_IN_USE: 'Email have been already used.',
    USER_NOT_EXISTS: "User don't exist",
    AUTH_CODE_NOT_FOUND: 'Something went wrong',
    INVALID_PASSWORD: 'Invalid password.',
    INVALID_TOKEN: 'Token is Invalid or expired!',
    VALID_TOKEN: 'Token is valid',
    UNAUTHORIZED_USER: 'You are not authorized!',
    RE_LOGIN: 'Please log in again',
    UPDATE: 'User updated Successfully!',
    DELETED: 'User deleted successfully!',
    GET_ALL: 'Get all users successfully',
  },
  AUTH: {
    REGISTER_SUCCESS: 'Account created successfully',
    LOGIN_SUCCESS: 'Login successful',
    LOGOUT_SUCCESS: 'Logged out successfully',
    LOGOUT_ALL_SUCCESS: 'Logged out from all devices successfully',
    REFRESH_SUCCESS: 'Token refreshed successfully',
    INVALID_CREDENTIALS: 'Invalid email or password',
    INVALID_REFRESH_TOKEN: 'Refresh token is invalid or expired',
    ACCOUNT_INACTIVE: 'Your account has been deactivated. Please contact support.',
    ACCOUNT_BANNED: 'Your account has been banned. Please contact support.',
    GOOGLE_ONLY_ACCOUNT: 'This account uses Google login. Please sign in with Google.',
    INVALID_TOKEN: 'Token is invalid or expired',
    EMAIL_ALREADY_VERIFIED: 'Email is already verified',
    EMAIL_VERIFICATION_SENT: 'Verification email sent',
    EMAIL_VERIFIED: 'Email verified successfully',
    FORGOT_PASSWORD_SENT: 'If an account exists with this email, you will receive a reset code',
    PASSWORD_RESET_SUCCESS: 'Password reset successfully',
    PASSWORD_CHANGED: 'Password changed successfully',
    PASSWORD_SET: 'Password set successfully',
    NO_PASSWORD_SET: 'This account has no password. Use set-password instead.',
    INVALID_CURRENT_PASSWORD: 'Current password is incorrect',
    PASSWORD_SAME_AS_CURRENT: 'New password must be different from current password',
    PASSWORD_ALREADY_SET: 'Password already set. Use change-password instead.',
    GOOGLE_LOGIN_SUCCESS: 'Google login successful',
    ACCOUNT_LINK_SUCCESS: 'Google account linked successfully',
  },
};
